### Rename taxa in otu table and RDP tax file
### Yorick Minnebo 28/11/2019

Change_taxaRDP <- function(RDP.df = RDPclass_QMP_merge, RDP = FALSE) {
if(RDP == FALSE){
  RDP.df$Taxa <- gsub("unclassified_(.+)","\\1_unclassified",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Escherichia/Shigella","Escherichia-Shigella",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Clostridium_sensu_stricto_1","Clostridium sensu stricto",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Ruminococcaceae_ge","Anaerotruncus",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Tyzzerella_3","Clostridium XlVb",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Erysipelotrichaceae_UCG-003","Clostridium XVIII",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Christensenellaceae_R-7_group","Dendrosporobacter",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Erysipelotrichaceae_ge","Erysipelotrichaceae_incertae_sedis",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Ruminococcaceae_UCG-004","Intestinimonas",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Macellibacteroides","Muribaculaceae_ge",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Ruminococcus_2","Ruminococcus",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("UBA1819","Subdoligranulum",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("unclassified_Enterobacteriaceae","Enterobacteriaceae_unclassified",RDP.df$Taxa)
} else {
  RDP.df$Taxa <- gsub("unclassified_(.+)","\\1_unclassified",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("\"Bacteroidales\"_unclassified","Bacteroidales_unclassified",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Clostridium XlVa","Clostridium_XlVa",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("\"Bacteroidetes\"_unclassified","Bacteroidetes_unclassified",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Clostridium sensu stricto", "Clostridium_sensu_stricto", RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Clostridium IV","Clostridium_IV",RDP.df$Taxa)
  RDP.df$Taxa <- gsub("Clostridium XlVb","Clostridium_XlVb",RDP.df$Taxa)
  }
  
 return(RDP.df) 
}

Change_taxaOTU <- function(OTU.df = otu.tab, RDP = FALSE) {
  if(RDP == FALSE){
    OTU.df$Genus <- gsub("CAG-352","Clostridium IV",OTU.df$Genus) #old to new
    OTU.df$Genus <- gsub("Family_XIII_unclassified","Eubacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnoclostridium","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnoclostridium_5","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_ge","Ruminococcus2",OTU.df$Genus)
    OTU.df$Genus <- gsub("Agathobacter","Lachnospiracea_incertae_sedis",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridium_sensu_stricto_1","Clostridium sensu stricto",OTU.df$Genus)
    OTU.df$Genus <- gsub("Bacteroidales_unclassified","Paraprevotella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridium XlVa_5","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Erysipelotrichaceae_UCG-003","Clostridium XVIII",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_UCG-004","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_ND3007_group","Lachnospiracea_incertae_sedis",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcus_2","Ruminococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("UBA1819","Subdoligranulum",OTU.df$Genus)
    OTU.df$Genus <- gsub("Christensenellaceae_R-7_group","Dendrosporobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Tyzzerella_3","Clostridium XlVb",OTU.df$Genus)
    OTU.df$Genus <- gsub("Eubacterium","Eubacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Coprococcus_3","Coprococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Coprococcus_2","Coprococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Erysipelotrichaceae_ge","Erysipelotrichaceae_incertae_sedis",OTU.df$Genus)
    OTU.df$Genus <- gsub("CAG-56","Ruminococcus2",OTU.df$Genus)
    OTU.df$Genus <- gsub("Coprococcus_1","Coprococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_NK4A136_group","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-004","Intestinimonas",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcus_1","Ruminococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-013","Sporobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("GCA-900066755","Lachnospiracea_incertae_sedis",OTU.df$Genus)
    OTU.df$Genus <- gsub("Sellimonas","Ruminococcus2",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-002","Oscillibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-014","Robinsoniella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_FCS020_group","Fusicatenibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_UCG-001","Ruminococcus2",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_ge","Anaerotruncus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Gastranaerophilales_ge","Vampirovibrio",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured_ge","Aestuariispira",OTU.df$Genus)
    OTU.df$Genus <- gsub("Candidatus_Soleaferrea","Ethanoligenens",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_NK4A214_group","Sporobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminiclostridium_6","Clostridium IV",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridiaceae_1_unclassified","Clostridium sensu stricto",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminiclostridium_5","Clostridium IV",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminiclostridium_9","Flavonifractor",OTU.df$Genus)
    OTU.df$Genus <- gsub("Prevotellaceae_NK3B31_group","Prevotella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Tyzzerella","Clostridium XlVb",OTU.df$Genus)
    OTU.df$Genus <- gsub("Mollicutes_RF39_ge","Bulleidia",OTU.df$Genus)
    OTU.df$Genus <- gsub("Hafnia-Obesumbacterium","Hafnia",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Slackia",OTU.df$Genus)
    OTU.df$Genus <- gsub("Bacteroidia_unclassified","Nubsella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-003","Oscillibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Prevotella_7","Prevotella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_UCG-003","Hungatella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Prevotella_2","Prevotella",OTU.df$Genus)
    OTU.df$Genus <- gsub("Oscillospira","Oscillibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-005","Sporobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-008","Butyricicoccus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Family_XIII_AD3011_group","Acidaminobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("GCA-900066575","Anaerosporobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Phocea","Acetanaerobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Adlercreutzia",OTU.df$Genus)
    OTU.df$Genus <- gsub("Family_XIII_UCG-001","Anaerovorax",OTU.df$Genus)
    OTU.df$Genus <- gsub("Lachnospiraceae_UCG-010","Clostridium XlVb",OTU.df$Genus)
    OTU.df$Genus <- gsub("Burkholderia-Caballeronia-Paraburkholderia","Burkholderia",OTU.df$Genus)
    OTU.df$Genus <- gsub("Defluviitaleaceae_UCG-011","Defluviitalea",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-009","Intestinimonas",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Oxobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Negativibacillus","Acetanaerobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Bacillaceae_unclassified","Bacillus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Erysipelatoclostridium","Clostridium XVIII",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured_ge","Olsenella",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured_ge","Parasporobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Raoultibacter","Gordonibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Mailhella","Bilophila",OTU.df$Genus)
    OTU.df$Genus <- gsub("UC5-1-2E3","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Anaerocolumna","Clostridium XlVa",OTU.df$Genus)
    OTU.df$Genus <- gsub("Fournierella","Faecalibacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Family_XIII_ge","Fusicatenibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Merdibacter","Faecalicoccus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Tannerellaceae_unclassified","Parabacteroides",OTU.df$Genus)
    OTU.df$Genus <- gsub("Proteobacteria_unclassified","Bilophila",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridiales_vadinBB60_group_ge","Anaerovibrio",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Coprobacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Clostridium IV",OTU.df$Genus)
    OTU.df$Genus <- gsub("DTU089","Clostridium IV",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-011","Ruminococcus",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Desulfitibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Eggerthellaceae_unclassified","Parvibacter",OTU.df$Genus)
    OTU.df$Genus <- gsub("Dielma","Anaerorhabdus",OTU.df$Genus)
    OTU.df$Genus <- gsub("Ruminococcaceae_UCG-010","Intestinimonas",OTU.df$Genus)
    OTU.df$Genus <- gsub("Caproiciproducens","Clostridium IV",OTU.df$Genus)
    OTU.df$Genus <- gsub("Harryflintia","Acetanaerobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("vadinBE97_ge","Oligosphaera",OTU.df$Genus)
    OTU.df$Genus <- gsub("Peptococcaceae_unclassified","Proteinivorax",OTU.df$Genus)
    OTU.df$Genus <- gsub("Fusobacteriaceae_unclassified","Fusobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Bacteroidetes_unclassified","Phocaeicola",OTU.df$Genus)
    OTU.df$Genus <- gsub("uncultured","Parasporobacterium",OTU.df$Genus)
    OTU.df$Genus <- gsub("Betaproteobacteriales_unclassified","Dechloromonas",OTU.df$Genus)
    OTU.df$Genus <- gsub("Rikenellaceae_unclassified","Alistipes",OTU.df$Genus)
  } else {
    OTU.df$Genus <- gsub("Clostridium_XVIII","Clostridium XVIII",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridium_XI","Clostridium XI",OTU.df$Genus)
    OTU.df$Genus <- gsub("Clostridiales_Incertae_Sedis_XIII_unclassified", "Clostridiales_Incertae Sedis XIII_unclassified", OTU.df$Genus)
    # OTU.df$Genus <- gsub("Escherichia/Shigella", "Escherichia-Shigella", OTU.df$Genus)
    OTU.df <- OTU.df
  }
  
  return(OTU.df) 
}
  