# papertheme function
# Original papertheme function from Kim De Paepe
# Adapted by Yorick Minnebo
# version 2020

### Input of function
#ggplot object without any formatting 

### WHAT THIS FUNCTION DOES
# Removes grey background
# 

### Arguments of function
# only the input object


papertheme <- function(ggplotobject, size = 20){
  library(ggplot2)  
  
  ggplotnewobject <- ggplotobject + theme_bw() +
                                                theme(axis.ticks.x = element_line(colour = "black"), 
                                                 axis.ticks.y =element_line(colour = "black"),
                                                 panel.background = element_rect(fill = "white"),
                                                 legend.position = "bottom",
                                                 panel.grid.major=element_blank(),
                                                 panel.grid.minor=element_blank(),
                                                 axis.line.x  = element_line(colour = "black"),
                                                 axis.line.y = element_line(colour="black"),
                                                 axis.text.x = element_text(size = size,family='sans',angle=0),
                                                 axis.text.y = element_text(size = size,family='sans',angle=0),
                                                 axis.title.x = element_text(size =size,family='sans',angle=0),
                                                 axis.title.y = element_text(size=size,family='sans',angle=90),
                                                 legend.text = element_text(size=size,family='sans',angle=0),
                                                 legend.title = element_text(size=size,family='sans',angle=0),
                                                 strip.background = element_rect(colour="white", fill="white"),
                                                 panel.border = element_rect(colour = "black"),
                                                 strip.text.y = element_text(size=size,angle=270,family='sans'),
                                                 legend.key.size = unit(1.5, 'lines'),
                                                 plot.title=element_text(size=size,family='sans',angle=0), 
                                                 strip.text.x = element_text(size = size))
  
  return(ggplotnewobject)  }


italicgenera <- function(ggplotobject){
  library(ggplot2) 
  
  ggplotnewobject <- ggplotobject + 
    scale_y_discrete(labels = c("Achromobacter" = expression(italic("Achromobacter")),
                                "Acidaminococcus" = expression(italic("Acidaminococcus")),
                                "Actinobacteria_unclassified" = expression(italic("Actinobacteria_unclassified")),
                                "Akkermansia" = expression(italic("Akkermansia")),
                                "Alistipes" = expression(italic("Alistipes")),
                                "Alphaproteobacteria" = expression(italic("Alphaproteobacteria")),
                                "Anaeroglobus" = expression(italic("Anaeroglobus")),
                                "Anaerostipes" = expression(italic("Anaerostipes")),
                                "Anaerotruncus" = expression(italic("Anaerotruncus")),
                                "Asaccharobacter" = expression(italic("Asaccharobacter")),
                                "Bacillales_unclassified" = expression(italic("Bacillales_unclassified")),
                                "Bacillus" = expression(italic("Bacillus")),
                                "Bacteria" = expression(italic("Bacteria")),
                                "Bacteroidales_unclassified" = expression(italic("Bacteroidales_unclassified")),
                                "Bacteroides" = expression(italic("Bacteroides")),
                                "Barnesiella" = expression(italic("Barnesiella")),
                                "Bifidobacterium" = expression(italic("Bifidobacterium")),
                                "Bilophila" = expression(italic("Bilophila")),
                                "Blautia" = expression(italic("Blautia")),
                                "Burkholderia" = expression(italic("Burkholderia")),
                                "Butyricicoccus" = expression(italic("Butyricicoccus")),
                                "Butyricimonas" = expression(italic("Butyricimonas")),
                                "Cloacibacillus" = expression(italic("Cloacibacillus")),
                                "Clostridiales" = expression(italic("Clostridiales")),
                                "Clostridiales_Incertae_Sedis_XIII_unclassified" = expression(italic("Clostridiales_Incertae_Sedis_XIII_unclassified")),
                                "Clostridium_IV" = expression(italic("Clostridium_IV")),
                                "Clostridium_sensu_stricto" = expression(italic("Clostridium_sensu_stricto")),
                                "Clostridium_XI" = expression(italic("Clostridium_XI")),
                                "Clostridium_XlVa" = expression(italic("Clostridium_XlVa")),
                                "Clostridium_XlVb" = expression(italic("Clostridium_XlVb")),
                                "Clostridium_XVIII" = expression(italic("Clostridium_XVIII")),
                                "Collinsella" = expression(italic("Collinsella")),
                                "Coprococcus" = expression(italic("Coprococcus")),
                                "Coriobacteriaceae_unclassified" = expression(italic("Coriobacteriaceae_unclassified")),
                                "Desulfovibrio" = expression(italic("Desulfovibrio")),
                                "Dialister" = expression(italic("Dialister")),
                                "Dorea" = expression(italic("Dorea")),
                                "Eggerthella" = expression(italic("Eggerthella")),
                                "Eisenbergiella" = expression(italic("Eisenbergiella")),
                                "Enterobacteriaceae" = expression(italic("Enterobacteriaceae")),
                                "Enterococcus" = expression(italic("Enterococcus")),
                                "Erysipelotrichaceae" = expression(italic("Erysipelotrichaceae")),
                                "Escherichia/Shigella" = expression(italic("Escherichia/Shigella")),
                                "Eubacteriaceae_unclassified" = expression(italic("Eubacteriaceae_unclassified")),
                                "Eubacterium" = expression(italic("Eubacterium")),
                                "Faecalibacterium" = expression(italic("Faecalibacterium")),
                                "Faecalicoccus" = expression(italic("Faecalicoccus")),
                                "Firmicutes" = expression(italic("Firmicutes")),
                                "Flavonifractor" = expression(italic("Flavonifractor")),
                                "Fusicatenibacter" = expression(italic("Fusicatenibacter")),
                                "Fusobacterium" = expression(italic("Fusobacterium")),
                                "Gammaproteobacteria_unclassified" = expression(italic("Gammaproteobacteria_unclassified")),
                                "Holdemanella" = expression(italic("Holdemanella")),
                                "Holdemania" = expression(italic("Holdemania")),
                                "Intestinibacter" = expression(italic("Intestinibacter")),
                                "Intestinimonas" = expression(italic("Intestinimonas")),
                                "Lachnospiraceae" = expression(italic("Lachnospiraceae")),
                                "Lactobacillus" = expression(italic("Lactobacillus")),
                                "Lactococcus" = expression(italic("Lactococcus")),
                                "Lysinibacillus" = expression(italic("Lysinibacillus")),
                                "Megamonas" = expression(italic("Megamonas")),
                                "Megasphaera" = expression(italic("Megasphaera")),
                                "Mitsuokella" = expression(italic("Mitsuokella")),
                                "Murimonas" = expression(italic("Murimonas")),
                                "Odoribacter" = expression(italic("Odoribacter")),
                                "Oscillibacter" = expression(italic("Oscillibacter")),
                                "Parabacteroides" = expression(italic("Parabacteroides")),
                                "Paraprevotella" = expression(italic("Paraprevotella")),
                                "Parasutterella" = expression(italic("Parasutterella")),
                                "Pediococcus" = expression(italic("Pediococcus")),
                                "Peptoniphilus" = expression(italic("Peptoniphilus")),
                                "Peptostreptococcaceae_unclassified" = expression(italic("Peptostreptococcaceae_unclassified")),
                                "Peptostreptococcus" = expression(italic("Peptostreptococcus")),
                                "Phascolarctobacterium" = expression(italic("Phascolarctobacterium")),
                                "Prevotella" = expression(italic("Prevotella")),
                                "Pseudoflavonifractor" = expression(italic("Pseudoflavonifractor")),
                                "Pseudomonadaceae" = expression(italic("Pseudomonadaceae")),
                                "Pseudomonas" = expression(italic("Pseudomonas")),
                                "Rhizobium" = expression(italic("Rhizobium")),
                                "Romboutsia" = expression(italic("Romboutsia")),
                                "Roseburia" = expression(italic("Roseburia")),
                                "Ruminococcaceae" = expression(italic("Ruminococcaceae")),
                                "Ruminococcus" = expression(italic("Ruminococcus")),
                                "Ruminococcus" = expression(italic("Ruminococcus")),
                                "Senegalimassilia" = expression(italic("Senegalimassilia")),
                                "Slackia" = expression(italic("Slackia")),
                                "Stenotrophomonas" = expression(italic("Stenotrophomonas")),
                                "Streptococcus" = expression(italic("Streptococcus")),
                                "Subdoligranulum" = expression(italic("Subdoligranulum")),
                                "Succiniclasticum" = expression(italic("Succiniclasticum")),
                                "Sutterella" = expression(italic("Sutterella")),
                                "Terrisporobacter" = expression(italic("Terrisporobacter")),
                                "Veillonella" = expression(italic("Veillonella")),
                                "Veillonellaceae" = expression(italic("Veillonellaceae")),
                                "Victivallis" = expression(italic("Victivallis"))
                                ))
  
  return(ggplotnewobject)  }



bolditalicgenera <- function(ggplotobject){
  library(ggplot2) 
  
  ggplotnewobject <- ggplotobject + 
    scale_y_discrete(labels = c("Achromobacter" = expression(bolditalic("Achromobacter")),
                                "Acidaminococcus" = expression(bolditalic("Acidaminococcus")),
                                "Actinobacteria_unclassified" = expression(bolditalic("Actinobacteria_unclassified")),
                                "Akkermansia" = expression(bolditalic("Akkermansia")),
                                "Alistipes" = expression(bolditalic("Alistipes")),
                                "Alphaproteobacteria" = expression(bolditalic("Alphaproteobacteria")),
                                "Anaeroglobus" = expression(bolditalic("Anaeroglobus")),
                                "Anaerostipes" = expression(bolditalic("Anaerostipes")),
                                "Anaerotruncus" = expression(bolditalic("Anaerotruncus")),
                                "Asaccharobacter" = expression(bolditalic("Asaccharobacter")),
                                "Bacillales_unclassified" = expression(bolditalic("Bacillales_unclassified")),
                                "Bacillus" = expression(bolditalic("Bacillus")),
                                "Bacteria" = expression(bolditalic("Bacteria")),
                                "Bacteroidales_unclassified" = expression(bolditalic("Bacteroidales_unclassified")),
                                "Bacteroides" = expression(bolditalic("Bacteroides")),
                                "Barnesiella" = expression(bolditalic("Barnesiella")),
                                "Bifidobacterium" = expression(bolditalic("Bifidobacterium")),
                                "Bilophila" = expression(bolditalic("Bilophila")),
                                "Blautia" = expression(bolditalic("Blautia")),
                                "Burkholderia" = expression(bolditalic("Burkholderia")),
                                "Butyricicoccus" = expression(bolditalic("Butyricicoccus")),
                                "Butyricimonas" = expression(bolditalic("Butyricimonas")),
                                "Cloacibacillus" = expression(bolditalic("Cloacibacillus")),
                                "Clostridiales" = expression(bolditalic("Clostridiales")),
                                "Clostridiales_Incertae_Sedis_XIII_unclassified" = expression(bolditalic("Clostridiales_Incertae_Sedis_XIII_unclassified")),
                                "Clostridium_IV" = expression(bolditalic("Clostridium_IV")),
                                "Clostridium_sensu_stricto" = expression(bolditalic("Clostridium_sensu_stricto")),
                                "Clostridium_XI" = expression(bolditalic("Clostridium_XI")),
                                "Clostridium_XlVa" = expression(bolditalic("Clostridium_XlVa")),
                                "Clostridium_XlVb" = expression(bolditalic("Clostridium_XlVb")),
                                "Clostridium_XVIII" = expression(bolditalic("Clostridium_XVIII")),
                                "Collinsella" = expression(bolditalic("Collinsella")),
                                "Coprococcus" = expression(bolditalic("Coprococcus")),
                                "Coriobacteriaceae_unclassified" = expression(bolditalic("Coriobacteriaceae_unclassified")),
                                "Desulfovibrio" = expression(bolditalic("Desulfovibrio")),
                                "Dialister" = expression(bolditalic("Dialister")),
                                "Dorea" = expression(bolditalic("Dorea")),
                                "Eggerthella" = expression(bolditalic("Eggerthella")),
                                "Eisenbergiella" = expression(bolditalic("Eisenbergiella")),
                                "Enterobacteriaceae" = expression(bolditalic("Enterobacteriaceae")),
                                "Enterococcus" = expression(bolditalic("Enterococcus")),
                                "Erysipelotrichaceae" = expression(bolditalic("Erysipelotrichaceae")),
                                "Escherichia/Shigella" = expression(bolditalic("Escherichia/Shigella")),
                                "Eubacteriaceae_unclassified" = expression(bolditalic("Eubacteriaceae_unclassified")),
                                "Eubacterium" = expression(bolditalic("Eubacterium")),
                                "Faecalibacterium" = expression(bolditalic("Faecalibacterium")),
                                "Faecalicoccus" = expression(bolditalic("Faecalicoccus")),
                                "Firmicutes" = expression(bolditalic("Firmicutes")),
                                "Flavonifractor" = expression(bolditalic("Flavonifractor")),
                                "Fusicatenibacter" = expression(bolditalic("Fusicatenibacter")),
                                "Fusobacterium" = expression(bolditalic("Fusobacterium")),
                                "Gammaproteobacteria_unclassified" = expression(bolditalic("Gammaproteobacteria_unclassified")),
                                "Holdemanella" = expression(bolditalic("Holdemanella")),
                                "Holdemania" = expression(bolditalic("Holdemania")),
                                "Intestinibacter" = expression(bolditalic("Intestinibacter")),
                                "Intestinimonas" = expression(bolditalic("Intestinimonas")),
                                "Lachnospiraceae" = expression(bolditalic("Lachnospiraceae")),
                                "Lactobacillus" = expression(bolditalic("Lactobacillus")),
                                "Lactococcus" = expression(bolditalic("Lactococcus")),
                                "Lysinibacillus" = expression(bolditalic("Lysinibacillus")),
                                "Megamonas" = expression(bolditalic("Megamonas")),
                                "Megasphaera" = expression(bolditalic("Megasphaera")),
                                "Mitsuokella" = expression(bolditalic("Mitsuokella")),
                                "Murimonas" = expression(bolditalic("Murimonas")),
                                "Odoribacter" = expression(bolditalic("Odoribacter")),
                                "Oscillibacter" = expression(bolditalic("Oscillibacter")),
                                "Parabacteroides" = expression(bolditalic("Parabacteroides")),
                                "Paraprevotella" = expression(bolditalic("Paraprevotella")),
                                "Parasutterella" = expression(bolditalic("Parasutterella")),
                                "Pediococcus" = expression(bolditalic("Pediococcus")),
                                "Peptoniphilus" = expression(bolditalic("Peptoniphilus")),
                                "Peptostreptococcaceae_unclassified" = expression(bolditalic("Peptostreptococcaceae_unclassified")),
                                "Peptostreptococcus" = expression(bolditalic("Peptostreptococcus")),
                                "Phascolarctobacterium" = expression(bolditalic("Phascolarctobacterium")),
                                "Prevotella" = expression(bolditalic("Prevotella")),
                                "Pseudoflavonifractor" = expression(bolditalic("Pseudoflavonifractor")),
                                "Pseudomonadaceae" = expression(bolditalic("Pseudomonadaceae")),
                                "Pseudomonas" = expression(bolditalic("Pseudomonas")),
                                "Rhizobium" = expression(bolditalic("Rhizobium")),
                                "Romboutsia" = expression(bolditalic("Romboutsia")),
                                "Roseburia" = expression(bolditalic("Roseburia")),
                                "Ruminococcaceae" = expression(bolditalic("Ruminococcaceae")),
                                "Ruminococcus" = expression(bolditalic("Ruminococcus")),
                                # "Ruminococcus" = expression(bolditalic("Ruminococcus")),
                                "Senegalimassilia" = expression(bolditalic("Senegalimassilia")),
                                "Slackia" = expression(bolditalic("Slackia")),
                                "Stenotrophomonas" = expression(bolditalic("Stenotrophomonas")),
                                "Streptococcus" = expression(bolditalic("Streptococcus")),
                                "Subdoligranulum" = expression(bolditalic("Subdoligranulum")),
                                "Succiniclasticum" = expression(bolditalic("Succiniclasticum")),
                                "Sutterella" = expression(bolditalic("Sutterella")),
                                "Terrisporobacter" = expression(bolditalic("Terrisporobacter")),
                                "Veillonella" = expression(bolditalic("Veillonella")),
                                "Veillonellaceae" = expression(bolditalic("Veillonellaceae")),
                                "Victivallis" = expression(bolditalic("Victivallis"))
    ))
  
  return(ggplotnewobject)  }






italicgeneralabels <- function(ggplotobject){
  library(ggplot2) 
  
  
  ggplotnewobject <- ggplotobject + 
    scale_fill_discrete(labels = c("Achromobacter" = expression(italic("Achromobacter")),
                                "Acidaminococcus" = expression(italic("Acidaminococcus")),
                                "Actinobacteria_unclassified" = expression(italic("Actinobacteria_unclassified")),
                                "Akkermansia" = expression(italic("Akkermansia")),
                                "Alistipes" = expression(italic("Alistipes")),
                                "Alphaproteobacteria" = expression(italic("Alphaproteobacteria")),
                                "Anaeroglobus" = expression(italic("Anaeroglobus")),
                                "Anaerostipes" = expression(italic("Anaerostipes")),
                                "Anaerotruncus" = expression(italic("Anaerotruncus")),
                                "Asaccharobacter" = expression(italic("Asaccharobacter")),
                                "Bacillales_unclassified" = expression(italic("Bacillales_unclassified")),
                                "Bacillus" = expression(italic("Bacillus")),
                                "Bacteria" = expression(italic("Bacteria")),
                                "Bacteroidales_unclassified" = expression(italic("Bacteroidales_unclassified")),
                                "Bacteroides" = expression(italic("Bacteroides")),
                                "Barnesiella" = expression(italic("Barnesiella")),
                                "Bifidobacterium" = expression(italic("Bifidobacterium")),
                                "Bilophila" = expression(italic("Bilophila")),
                                "Blautia" = expression(italic("Blautia")),
                                "Burkholderia" = expression(italic("Burkholderia")),
                                "Butyricicoccus" = expression(italic("Butyricicoccus")),
                                "Butyricimonas" = expression(italic("Butyricimonas")),
                                "Cloacibacillus" = expression(italic("Cloacibacillus")),
                                "Clostridiales" = expression(italic("Clostridiales")),
                                "Clostridiales_Incertae_Sedis_XIII_unclassified" = expression(italic("Clostridiales_Incertae_Sedis_XIII_unclassified")),
                                "Clostridium_IV" = expression(italic("Clostridium_IV")),
                                "Clostridium_sensu_stricto" = expression(italic("Clostridium_sensu_stricto")),
                                "Clostridium_XI" = expression(italic("Clostridium_XI")),
                                "Clostridium_XlVa" = expression(italic("Clostridium_XlVa")),
                                "Clostridium_XlVb" = expression(italic("Clostridium_XlVb")),
                                "Clostridium_XVIII" = expression(italic("Clostridium_XVIII")),
                                "Collinsella" = expression(italic("Collinsella")),
                                "Coprococcus" = expression(italic("Coprococcus")),
                                "Coriobacteriaceae_unclassified" = expression(italic("Coriobacteriaceae_unclassified")),
                                "Desulfovibrio" = expression(italic("Desulfovibrio")),
                                "Dialister" = expression(italic("Dialister")),
                                "Dorea" = expression(italic("Dorea")),
                                "Eggerthella" = expression(italic("Eggerthella")),
                                "Eisenbergiella" = expression(italic("Eisenbergiella")),
                                "Enterobacteriaceae" = expression(italic("Enterobacteriaceae")),
                                "Enterococcus" = expression(italic("Enterococcus")),
                                "Erysipelotrichaceae" = expression(italic("Erysipelotrichaceae")),
                                "Escherichia/Shigella" = expression(italic("Escherichia/Shigella")),
                                "Eubacteriaceae_unclassified" = expression(italic("Eubacteriaceae_unclassified")),
                                "Eubacterium" = expression(italic("Eubacterium")),
                                "Faecalibacterium" = expression(italic("Faecalibacterium")),
                                "Faecalicoccus" = expression(italic("Faecalicoccus")),
                                "Firmicutes" = expression(italic("Firmicutes")),
                                "Flavonifractor" = expression(italic("Flavonifractor")),
                                "Fusicatenibacter" = expression(italic("Fusicatenibacter")),
                                "Fusobacterium" = expression(italic("Fusobacterium")),
                                "Gammaproteobacteria_unclassified" = expression(italic("Gammaproteobacteria_unclassified")),
                                "Holdemanella" = expression(italic("Holdemanella")),
                                "Holdemania" = expression(italic("Holdemania")),
                                "Intestinibacter" = expression(italic("Intestinibacter")),
                                "Intestinimonas" = expression(italic("Intestinimonas")),
                                "Lachnospiraceae" = expression(italic("Lachnospiraceae")),
                                "Lactobacillus" = expression(italic("Lactobacillus")),
                                "Lactococcus" = expression(italic("Lactococcus")),
                                "Lysinibacillus" = expression(italic("Lysinibacillus")),
                                "Megamonas" = expression(italic("Megamonas")),
                                "Megasphaera" = expression(italic("Megasphaera")),
                                "Mitsuokella" = expression(italic("Mitsuokella")),
                                "Murimonas" = expression(italic("Murimonas")),
                                "Odoribacter" = expression(italic("Odoribacter")),
                                "Oscillibacter" = expression(italic("Oscillibacter")),
                                "Parabacteroides" = expression(italic("Parabacteroides")),
                                "Paraprevotella" = expression(italic("Paraprevotella")),
                                "Parasutterella" = expression(italic("Parasutterella")),
                                "Pediococcus" = expression(italic("Pediococcus")),
                                "Peptoniphilus" = expression(italic("Peptoniphilus")),
                                "Peptostreptococcaceae_unclassified" = expression(italic("Peptostreptococcaceae_unclassified")),
                                "Peptostreptococcus" = expression(italic("Peptostreptococcus")),
                                "Phascolarctobacterium" = expression(italic("Phascolarctobacterium")),
                                "Prevotella" = expression(italic("Prevotella")),
                                "Pseudoflavonifractor" = expression(italic("Pseudoflavonifractor")),
                                "Pseudomonadaceae" = expression(italic("Pseudomonadaceae")),
                                "Pseudomonas" = expression(italic("Pseudomonas")),
                                "Rhizobium" = expression(italic("Rhizobium")),
                                "Romboutsia" = expression(italic("Romboutsia")),
                                "Roseburia" = expression(italic("Roseburia")),
                                "Ruminococcaceae" = expression(italic("Ruminococcaceae")),
                                "Ruminococcus" = expression(italic("Ruminococcus")),
                                "Ruminococcus" = expression(italic("Ruminococcus")),
                                "Senegalimassilia" = expression(italic("Senegalimassilia")),
                                "Slackia" = expression(italic("Slackia")),
                                "Stenotrophomonas" = expression(italic("Stenotrophomonas")),
                                "Streptococcus" = expression(italic("Streptococcus")),
                                "Subdoligranulum" = expression(italic("Subdoligranulum")),
                                "Succiniclasticum" = expression(italic("Succiniclasticum")),
                                "Sutterella" = expression(italic("Sutterella")),
                                "Terrisporobacter" = expression(italic("Terrisporobacter")),
                                "Veillonella" = expression(italic("Veillonella")),
                                "Veillonellaceae" = expression(italic("Veillonellaceae")),
                                "Victivallis" = expression(italic("Victivallis"))
    ))
  
  return(ggplotnewobject)  }


whale2 <- c("                                  ','. '. ; : ,','\n",
            "                                    '..'.,',..'\n",
            "                                       ';.'  ,'\n",
            "                                        ;;\n",
            "                                        ;'\n",
            "                          :._   _.------------.___\n",
            "                  __      :__:-'                  '--.\n",
            "           __   ,' .'    .'             ______________'.\n",
            "         /__ '.-  ____.'          0  .' .'  .'  _.-_.'\n",
            "            '._YM                 .-': .' _.' _.'_.'\n",
            "             '----'._____________.'_'._:_:_.-'--'\n",
            "                          \n",
            "                       HAPPY WHALE IS HAPPY"
) 

whale3 <- c("                                      WELL DONE\n",
            "                                  ','. '. ; : ,','\n",
            "                                    '..'.,',..'\n",
            "                                       ';.'  ,'\n",
            "                                        ;;\n",
            "                                        ;'\n",
            "                          :._   _.------------.___\n",
            "                  __      :__:-'                  '--.\n",
            "           __   ,' .'    .'             ______________'.\n",
            "         /__ '.-  ____.'          0  .' .'  .'  _.-_.'\n",
            "            '._YM                 .-': .' _.' _.'_.'\n",
            "             '----'._____________.'_'._:_:_.-'--'\n",
            "                          \n",
            "                       HAPPY WHALE IS HAPPY"
) 
